### ISSUE TITLE
core-setup build script requires quoted arguments on Gentoo

### ISSUE THREAD

**Issue by eyoung100** [mellinoe/bootstrap#4]
The binaries we need to copy are now in the core-setup directory, not in the coreclr directory. but that I can't fix without help

**Comment by mellinoe** [comment]
Could you clarify which step you are talking about? The build script copies native binaries from both subdirectories into `dotnetcli`. The runtime (CoreCLR) comes from the `coreclr/bin/Product/...` directory, and the "shared host" (`dotnet`, `libhostfxr`, `libhostpolicy`) come from subdirectories in core-setup. We need things from both in order to get a working bootstrap CLI.

**Comment by eyoung100** [comment]
Issue now fixed via your comment in PR #3.  All other PR's closed, and needed fix needs to be merged in via PR #7

**Comment by mellinoe** [comment]
@eyoung100 Does the current version work for you? Technically it has a couple of extra changes over what you submitted, but those should help rather than hurt anything.

**Comment by eyoung100** [comment]
It does work, and great I might add.  See the thread over in dotnet/cli #4187.  If you have any questions regarding your Gentoo efforts, or need further help modifying/updating your great script, please contact me via email or Twitter username @eyoung100.  I'll leave this open for acknowledgement purposes, after which you're free to close.

**Comment by mellinoe** [comment]
Thanks for the confirmation, @eyoung100 .
